import Head from "next/head";
import ShowJoke from "./ShowJoke";
export default function Home() {
  const fetchJoke = async () => {
    const jokeResponse = await fetch(`https://v2.jokeapi.dev/joke/Any`);
    const jokeInfo = await jokeResponse.json();
    const data = {
      id: jokeInfo.id,
      setup: jokeInfo.setup,
      delivery: jokeInfo.delivery,
    };
    console.log(data);
    <ShowJoke data={data} />;
  };
  fetchJoke();
  return (
    <>
      <Head>
        <title>Create </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <ShowJoke />
        </div>
      </main>
    </>
  );
}
